import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import chatRouter from "./chat.js";
import summaryRouter from "./summary.js";
import analysisRouter from "./analysis.js";
import insightsRouter from "./insights.js";
import orgRouter from "./org.js";
import membersRouter from "./members.js";
import userRouter from "./user.js";
import checkoutRouter from "./checkout.js";
import subscribeRouter from "./subscribe.js";
import stripeWebhookRouter from "./stripeWebhook.js";
import hostnameRouter from "./hostname.js";
import conversationsRouter from "./conversations.js";
import analysisExportRouter from "./analysisExport.js";
import teamRouter from "./team.js";
import usageRouter from "./usage.js";
import chatTagRouter from "./chatTag.js";
import stripePortalRouter from "./stripePortal.js";
import userCheckRouter from "./userCheck.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(chatRouter);
router.use(summaryRouter);
router.use(analysisRouter);
router.use(analysisExportRouter);
router.use(insightsRouter);
router.use(orgRouter);
router.use(membersRouter);
router.use(teamRouter);
router.use(userRouter);
router.use(checkoutRouter);
router.use(subscribeRouter);
router.use(stripeWebhookRouter);
router.use(hostnameRouter);
router.use(conversationsRouter);
router.use(usageRouter);
router.use(chatTagRouter);
router.use(stripePortalRouter);
router.use(userCheckRouter);

export default router;
